name: flashcard
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  logging: ^1.2.0
  flutter_bloc: ^8.1.3
  flutter_iconpicker: 3.3.3
  shared_preferences: ^2.2.0
  flutter_markdown: ^0.7.1
  firebase_auth: ^4.17.4
  l10n_mapper_generator: ^2.0.0
  cloud_firestore: ^4.15.5
  latlong2: ^0.9.0
  location: ^6.0.1
  flutter_localizations:
    sdk: flutter
  intl: any
  icon_picker: ^2.1.0
  firebase_storage: ^11.2.2
  country_flags: ^2.2.0
  firebase_core_web: ^2.11.0
  firebase_core: ^2.12.0  # Replace with a version compatible with firebase_core_web ^2.11.0
  flutter_launcher_icons: ^0.9.2
  google_sign_in: ^6.2.1
  flutter_intl: ^0.0.1
  firebase_ui_oauth_google: ^1.3.2


flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: false

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  generate: true
    - gen_l10n

  uses-material-design: true

  assets:
    - assets/animations/cards/

  fonts:
    - family: EducationIcons
      fonts:
        - asset: fonts/EducationIcons.ttf


flutter_intl:
  enabled: true
  arb_path: lib/l10n
  template_ar_file: lib/l10n/intl_en.arb
  output_dir: lib/generated